const TRANSLATIONS = {
  us: {
    code: "us",
    lang: "en",
    name: "United States",
    flag: "🇺🇸",
    label: "English",
    siteName: "Green Global",
    siteSuffix: "Funds",
    navHome: "Home",
    navAbout: "About Us",
    navServices: "Services",
    navHow: "How It Works",
    navBlog: "Blog",
    navContact: "Contact",
    signIn: "Sign In",
    signUp: "Sign Up",
    badgeWelcome: "Welcome to Green Global Funds",
    headline: "Grow Your Money.",
    headlineGreen: "Secure Your Future.",
    heroText: "Green Global Funds helps you save, invest and grow your money with secure, reliable and profitable financial solutions.",
    getStarted: "Get Started",
    learnMore: "Learn More",
    featSecure: "Secure & Trusted",
    featSecureDesc: "Bank-level security to keep your funds safe.",
    featReturns: "High Returns",
    featReturnsDesc: "Competitive returns that help your money grow faster.",
    featFast: "Easy & Fast",
    featFastDesc: "Simple processes, quick transactions.",
    featSupport: "24/7 Support",
    featSupportDesc: "We are here to help you anytime, anywhere.",
    ourServices: "Our Services",
    serviceTitle: "Smart Financial Solutions<br>for a Better Tomorrow",
    serviceSavings: "Savings",
    serviceSavingsDesc: "Secure your future with flexible savings plans designed for you.",
    serviceInvest: "Investments",
    serviceInvestDesc: "Grow your wealth with profitable and secure investment opportunities.",
    serviceLoans: "Loans",
    serviceLoansDesc: "Get quick and flexible loans with easy repayment options.",
    serviceInsurance: "Insurance",
    serviceInsuranceDesc: "Protect what matters most with reliable insurance solutions.",
    chooseBadge: "Why Choose Us",
    chooseTitle: "Your Trust, Our<br>Commitment",
    chooseText: "At Green Global Funds, we are committed to providing transparent, reliable, and innovative financial services that help you achieve your financial goals.",
    footerRights: "&copy; 2026 Green Global Funds. All rights reserved.",
    selectCountry: "Select Your Country",
    selectCountryDesc: "Choose your country to get started with the best experience.",
    continue: "Continue",
    backToHome: "Back to Home",
    signInTitle: "Sign In",
    signInSub: "Enter your details to access your account",
    email: "Email Address",
    password: "Password",
    rememberMe: "Remember Me",
    forgotPassword: "Forgot Password?",
    signInBtn: "Sign In",
    or: "or",
    signInGoogle: "Sign in with Google",
    noAccount: "Don't have an account?",
    signUpLink: "Sign Up",
    welcomeBack: "Welcome Back!",
    signInDesc: "Sign in to your account and continue your financial journey with confidence.",
    secureLogin: "Secure Login",
    fastAccess: "Fast & Easy Access",
    manageAccount: "Manage Your Account",
    createAccount: "Create Your Account",
    signUpDesc: "Join thousands of people who trust Green Global Funds to grow their money securely.",
    secureSafe: "Secure & Safe",
    easyReg: "Easy Registration",
    startGrowing: "Start Growing Today",
    signUpTitle: "Sign Up",
    signUpSub: "Create your Green Global Funds account",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    confirmPass: "Confirm Password",
    agreeTerms: "I agree to the",
    termsAndCond: "Terms and Conditions",
    and: "and",
    privacyPolicy: "Privacy Policy",
    createAccountBtn: "Create Account",
    alreadyAccount: "Already have an account?",
    addressInfo: "Address Information",
    streetLabel: "Street & House Number",
    streetPlaceholder: "Enter street and house number",
    postalLabel: "Postal Code",
    postalPlaceholder: "Enter postal code",
    cityLabel: "City",
    cityPlaceholder: "Enter your city",
    stateLabel: "State / Federal State",
    selectState: "Select state",
    countryLabel: "Country",
    back: "Back",
    continueBtn: "Continue",
    dashboardTitle: "Dashboard",
    dashboardSub: "Welcome back, John! Here's your financial overview.",
    navDashboard: "Dashboard",
    navAccounts: "Accounts",
    navTransactions: "Transactions",
    navInvestments: "Investments",
    navSavings: "Savings",
    navLoans: "Loans",
    navSettings: "Settings",
    signOut: "Sign Out",
    demoUser: "John Doe",
    totalBalance: "Total Balance",
    income: "Income",
    expenses: "Expenses",
    savingsGoal: "Savings Goal",
    goalProgress: "68% of $12,000 goal",
    investmentsGrowth: "Investments",
    investmentReturn: "+$940.00 this quarter",
    activeLoans: "Active Loans",
    nextPayment: "Next payment: Apr 15",
    insuranceCoverage: "Insurance",
    fullyCovered: "Fully Covered",
    coverageType: "Life & Health",
    recentTransactions: "Recent Transactions",
    viewAll: "View All",
    quickActions: "Quick Actions",
    transfer: "Transfer",
    payBills: "Pay Bills",
    invest: "Invest",
    deposit: "Deposit",
    currencyConverter: "Currency Converter",
    cardInfo: "Debit Card Information",
    cardNumber: "Card Number",
    cardholderName: "Cardholder Name",
    expiryDate: "Expiry Date",
    cvv: "CVV",
    cardPlaceholder: "1234 5678 9012 3456",
    namePlaceholder: "Full Name on Card",
    expiryPlaceholder: "MM/YY",
    cvvPlaceholder: "123",
    addCard: "Add Card",
    skipStep: "Skip for now"
  },
  gb: {
    code: "gb",
    lang: "en",
    name: "United Kingdom",
    flag: "🇬🇧",
    label: "English",
    siteName: "Green Global",
    siteSuffix: "Funds",
    navHome: "Home",
    navAbout: "About Us",
    navServices: "Services",
    navHow: "How It Works",
    navBlog: "Blog",
    navContact: "Contact",
    signIn: "Sign In",
    signUp: "Sign Up",
    badgeWelcome: "Welcome to Green Global Funds",
    headline: "Grow Your Money.",
    headlineGreen: "Secure Your Future.",
    heroText: "Green Global Funds helps you save, invest and grow your money with secure, reliable and profitable financial solutions.",
    getStarted: "Get Started",
    learnMore: "Learn More",
    featSecure: "Secure & Trusted",
    featSecureDesc: "Bank-level security to keep your funds safe.",
    featReturns: "High Returns",
    featReturnsDesc: "Competitive returns that help your money grow faster.",
    featFast: "Easy & Fast",
    featFastDesc: "Simple processes, quick transactions.",
    featSupport: "24/7 Support",
    featSupportDesc: "We are here to help you anytime, anywhere.",
    ourServices: "Our Services",
    serviceTitle: "Smart Financial Solutions<br>for a Better Tomorrow",
    serviceSavings: "Savings",
    serviceSavingsDesc: "Secure your future with flexible savings plans designed for you.",
    serviceInvest: "Investments",
    serviceInvestDesc: "Grow your wealth with profitable and secure investment opportunities.",
    serviceLoans: "Loans",
    serviceLoansDesc: "Get quick and flexible loans with easy repayment options.",
    serviceInsurance: "Insurance",
    serviceInsuranceDesc: "Protect what matters most with reliable insurance solutions.",
    chooseBadge: "Why Choose Us",
    chooseTitle: "Your Trust, Our<br>Commitment",
    chooseText: "At Green Global Funds, we are committed to providing transparent, reliable, and innovative financial services that help you achieve your financial goals.",
    footerRights: "&copy; 2026 Green Global Funds. All rights reserved.",
    selectCountry: "Select Your Country",
    selectCountryDesc: "Choose your country to get started with the best experience.",
    continue: "Continue",
    backToHome: "Back to Home",
    signInTitle: "Sign In",
    signInSub: "Enter your details to access your account",
    email: "Email Address",
    password: "Password",
    rememberMe: "Remember Me",
    forgotPassword: "Forgot Password?",
    signInBtn: "Sign In",
    or: "or",
    signInGoogle: "Sign in with Google",
    noAccount: "Don't have an account?",
    signUpLink: "Sign Up",
    welcomeBack: "Welcome Back!",
    signInDesc: "Sign in to your account and continue your financial journey with confidence.",
    secureLogin: "Secure Login",
    fastAccess: "Fast & Easy Access",
    manageAccount: "Manage Your Account",
    createAccount: "Create Your Account",
    signUpDesc: "Join thousands of people who trust Green Global Funds to grow their money securely.",
    secureSafe: "Secure & Safe",
    easyReg: "Easy Registration",
    startGrowing: "Start Growing Today",
    signUpTitle: "Sign Up",
    signUpSub: "Create your Green Global Funds account",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    confirmPass: "Confirm Password",
    agreeTerms: "I agree to the",
    termsAndCond: "Terms and Conditions",
    and: "and",
    privacyPolicy: "Privacy Policy",
    createAccountBtn: "Create Account",
    alreadyAccount: "Already have an account?",
    addressInfo: "Address Information",
    streetLabel: "Street & House Number",
    streetPlaceholder: "Enter street and house number",
    postalLabel: "Postal Code",
    postalPlaceholder: "Enter postal code",
    cityLabel: "City",
    cityPlaceholder: "Enter your city",
    stateLabel: "State / Federal State",
    selectState: "Select state",
    countryLabel: "Country",
    back: "Back",
    continueBtn: "Continue",
    dashboardTitle: "Dashboard",
    dashboardSub: "Welcome back, John! Here's your financial overview.",
    navDashboard: "Dashboard",
    navAccounts: "Accounts",
    navTransactions: "Transactions",
    navInvestments: "Investments",
    navSavings: "Savings",
    navLoans: "Loans",
    navSettings: "Settings",
    signOut: "Sign Out",
    demoUser: "John Doe",
    totalBalance: "Total Balance",
    income: "Income",
    expenses: "Expenses",
    savingsGoal: "Savings Goal",
    goalProgress: "68% of $12,000 goal",
    investmentsGrowth: "Investments",
    investmentReturn: "+$940.00 this quarter",
    activeLoans: "Active Loans",
    nextPayment: "Next payment: Apr 15",
    insuranceCoverage: "Insurance",
    fullyCovered: "Fully Covered",
    coverageType: "Life & Health",
    recentTransactions: "Recent Transactions",
    viewAll: "View All",
    quickActions: "Quick Actions",
    transfer: "Transfer",
    payBills: "Pay Bills",
    invest: "Invest",
    deposit: "Deposit",
    currencyConverter: "Currency Converter",
    cardInfo: "Debit Card Information",
    cardNumber: "Card Number",
    cardholderName: "Cardholder Name",
    expiryDate: "Expiry Date",
    cvv: "CVV",
    cardPlaceholder: "1234 5678 9012 3456",
    namePlaceholder: "Full Name on Card",
    expiryPlaceholder: "MM/YY",
    cvvPlaceholder: "123",
    addCard: "Add Card",
    skipStep: "Skip for now"
  },
  de: {
    code: "de",
    lang: "de",
    name: "Germany",
    flag: "🇩🇪",
    label: "Deutsch",
    siteName: "Grün Global",
    siteSuffix: "Fonds",
    navHome: "Startseite",
    navAbout: "Über uns",
    navServices: "Dienstleistungen",
    navHow: "So funktioniert's",
    navBlog: "Blog",
    navContact: "Kontakt",
    signIn: "Anmelden",
    signUp: "Registrieren",
    badgeWelcome: "Willkommen bei Green Global Funds",
    headline: "Lass dein Geld wachsen.",
    headlineGreen: "Sichere deine Zukunft.",
    heroText: "Green Global Funds hilft dir, dein Geld mit sicheren, zuverlässigen und profitablen Finanzlösungen zu sparen, zu investieren und zu vermehren.",
    getStarted: "Loslegen",
    learnMore: "Mehr erfahren",
    featSecure: "Sicher & Vertrauenswürdig",
    featSecureDesc: "Bankensicherheit, um deine Gelder zu schützen.",
    featReturns: "Hohe Renditen",
    featReturnsDesc: "Wettbewerbsfähige Renditen, die dein Geld schneller wachsen lassen.",
    featFast: "Einfach & Schnell",
    featFastDesc: "Einfache Prozesse, schnelle Transaktionen.",
    featSupport: "24/7 Support",
    featSupportDesc: "Wir sind jederzeit und überall für dich da.",
    ourServices: "Unsere Dienstleistungen",
    serviceTitle: "Intelligente Finanzlösungen<br>für eine bessere Zukunft",
    serviceSavings: "Sparen",
    serviceSavingsDesc: "Sichere deine Zukunft mit flexiblen Sparplänen, die auf dich zugeschnitten sind.",
    serviceInvest: "Investitionen",
    serviceInvestDesc: "Vermehre dein Vermögen mit profitablen und sicheren Anlagemöglichkeiten.",
    serviceLoans: "Kredite",
    serviceLoansDesc: "Erhalte schnelle und flexible Kredite mit einfachen Rückzahlungsoptionen.",
    serviceInsurance: "Versicherung",
    serviceInsuranceDesc: "Schütze, was dir wichtig ist, mit zuverlässigen Versicherungslösungen.",
    chooseBadge: "Warum uns wählen",
    chooseTitle: "Dein Vertrauen, unser<br>Engagement",
    chooseText: "Bei Green Global Funds verpflichten wir uns zu transparenten, zuverlässigen und innovativen Finanzdienstleistungen, die dir helfen, deine finanziellen Ziele zu erreichen.",
    footerRights: "&copy; 2026 Green Global Funds. Alle Rechte vorbehalten.",
    selectCountry: "Wähle dein Land",
    selectCountryDesc: "Wähle dein Land, um mit der besten Erfahrung zu starten.",
    continue: "Weiter",
    backToHome: "Zurück zur Startseite",
    signInTitle: "Anmelden",
    signInSub: "Gib deine Daten ein, um auf dein Konto zuzugreifen",
    email: "E-Mail-Adresse",
    password: "Passwort",
    rememberMe: "Angemeldet bleiben",
    forgotPassword: "Passwort vergessen?",
    signInBtn: "Anmelden",
    or: "oder",
    signInGoogle: "Mit Google anmelden",
    noAccount: "Noch kein Konto?",
    signUpLink: "Registrieren",
    welcomeBack: "Willkommen zurück!",
    signInDesc: "Melde dich in deinem Konto an und setze deine finanzielle Reise mit Zuversicht fort.",
    secureLogin: "Sicheres Login",
    fastAccess: "Schneller & einfacher Zugriff",
    manageAccount: "Verwalte dein Konto",
    createAccount: "Erstelle dein Konto",
    signUpDesc: "Schließe dich Tausenden von Menschen an, die Green Global Funds vertrauen, um ihr Geld sicher zu vermehren.",
    secureSafe: "Sicher & Geschützt",
    easyReg: "Einfache Registrierung",
    startGrowing: "Noch heute wachsen",
    signUpTitle: "Registrieren",
    signUpSub: "Erstelle dein Green Global Funds Konto",
    fullName: "Vollständiger Name",
    phoneNumber: "Telefonnummer",
    confirmPass: "Passwort bestätigen",
    agreeTerms: "Ich stimme zu",
    termsAndCond: "Allgemeine Geschäftsbedingungen",
    and: "und",
    privacyPolicy: "Datenschutzerklärung",
    createAccountBtn: "Konto erstellen",
    alreadyAccount: "Bereits ein Konto?",
    addressInfo: "Adressinformationen",
    streetLabel: "Straße & Hausnummer",
    streetPlaceholder: "Straße und Hausnummer eingeben",
    postalLabel: "Postleitzahl",
    postalPlaceholder: "Postleitzahl eingeben",
    cityLabel: "Stadt",
    cityPlaceholder: "Stadt eingeben",
    stateLabel: "Bundesland",
    selectState: "Bundesland wählen",
    countryLabel: "Land",
    back: "Zurück",
    continueBtn: "Weiter",
    dashboardTitle: "Dashboard",
    dashboardSub: "Willkommen zurück, John! Hier ist deine Finanzübersicht.",
    navDashboard: "Dashboard",
    navAccounts: "Konten",
    navTransactions: "Transaktionen",
    navInvestments: "Investitionen",
    navSavings: "Sparen",
    navLoans: "Kredite",
    navSettings: "Einstellungen",
    signOut: "Abmelden",
    demoUser: "John Doe",
    totalBalance: "Gesamtguthaben",
    income: "Einkommen",
    expenses: "Ausgaben",
    savingsGoal: "Sparziel",
    goalProgress: "68% von 12.000 $ Ziel",
    investmentsGrowth: "Investitionen",
    investmentReturn: "+940,00 $ in diesem Quartal",
    activeLoans: "Aktive Kredite",
    nextPayment: "Nächste Zahlung: 15. Apr",
    insuranceCoverage: "Versicherung",
    fullyCovered: "Vollständig abgesichert",
    coverageType: "Leben & Gesundheit",
    recentTransactions: "Letzte Transaktionen",
    viewAll: "Alle anzeigen",
    quickActions: "Schnellaktionen",
    transfer: "Überweisen",
    payBills: "Rechnungen",
    invest: "Investieren",
    deposit: "Einzahlen",
    currencyConverter: "Währungsrechner",
    cardInfo: "Debitkarteninformationen",
    cardNumber: "Kartennummer",
    cardholderName: "Karteninhaber",
    expiryDate: "Ablaufdatum",
    cvv: "CVV",
    cardPlaceholder: "1234 5678 9012 3456",
    namePlaceholder: "Vollständiger Name auf der Karte",
    expiryPlaceholder: "MM/JJ",
    cvvPlaceholder: "123",
    addCard: "Karte hinzufügen",
    skipStep: "Später überspringen"
  },
  fr: {
    code: "fr",
    lang: "fr",
    name: "France",
    flag: "🇫🇷",
    label: "Français",
    siteName: "Vert Global",
    siteSuffix: "Fonds",
    navHome: "Accueil",
    navAbout: "À propos",
    navServices: "Services",
    navHow: "Comment ça marche",
    navBlog: "Blog",
    navContact: "Contact",
    signIn: "Connexion",
    signUp: "Inscription",
    badgeWelcome: "Bienvenue chez Green Global Funds",
    headline: "Faites fructifier votre argent.",
    headlineGreen: "Sécurisez votre avenir.",
    heroText: "Green Global Funds vous aide à épargner, investir et faire fructifier votre argent avec des solutions financières sûres, fiables et rentables.",
    getStarted: "Commencer",
    learnMore: "En savoir plus",
    featSecure: "Sûr & Fiable",
    featSecureDesc: "Sécurité de niveau bancaire pour protéger vos fonds.",
    featReturns: "Hauts rendements",
    featReturnsDesc: "Des rendements compétitifs qui aident votre argent à croître plus vite.",
    featFast: "Facile & Rapide",
    featFastDesc: "Processus simples, transactions rapides.",
    featSupport: "Support 24/7",
    featSupportDesc: "Nous sommes là pour vous aider à tout moment, partout.",
    ourServices: "Nos Services",
    serviceTitle: "Solutions financières intelligentes<br>pour un avenir meilleur",
    serviceSavings: "Épargne",
    serviceSavingsDesc: "Sécurisez votre avenir avec des plans d'épargne flexibles conçus pour vous.",
    serviceInvest: "Investissements",
    serviceInvestDesc: "Faites croître votre patrimoine avec des opportunités d'investissement rentables et sécurisées.",
    serviceLoans: "Prêts",
    serviceLoansDesc: "Obtenez des prêts rapides et flexibles avec des options de remboursement faciles.",
    serviceInsurance: "Assurance",
    serviceInsuranceDesc: "Protégez ce qui compte le plus avec des solutions d'assurance fiables.",
    chooseBadge: "Pourquoi nous choisir",
    chooseTitle: "Votre confiance, notre<br>engagement",
    chooseText: "Chez Green Global Funds, nous nous engageons à fournir des services financiers transparents, fiables et innovants qui vous aident à atteindre vos objectifs financiers.",
    footerRights: "&copy; 2026 Green Global Funds. Tous droits réservés.",
    selectCountry: "Sélectionnez votre pays",
    selectCountryDesc: "Choisissez votre pays pour commencer avec la meilleure expérience.",
    continue: "Continuer",
    backToHome: "Retour à l'accueil",
    signInTitle: "Connexion",
    signInSub: "Entrez vos coordonnées pour accéder à votre compte",
    email: "Adresse e-mail",
    password: "Mot de passe",
    rememberMe: "Se souvenir de moi",
    forgotPassword: "Mot de passe oublié ?",
    signInBtn: "Se connecter",
    or: "ou",
    signInGoogle: "Se connecter avec Google",
    noAccount: "Vous n'avez pas de compte ?",
    signUpLink: "S'inscrire",
    welcomeBack: "Bon retour !",
    signInDesc: "Connectez-vous à votre compte et poursuivez votre parcours financier en toute confiance.",
    secureLogin: "Connexion sécurisée",
    fastAccess: "Accès rapide et facile",
    manageAccount: "Gérez votre compte",
    createAccount: "Créez votre compte",
    signUpDesc: "Rejoignez des milliers de personnes qui font confiance à Green Global Funds pour faire fructifier leur argent en toute sécurité.",
    secureSafe: "Sécurisé & sûr",
    easyReg: "Inscription facile",
    startGrowing: "Commencez à grandir dès aujourd'hui",
    signUpTitle: "Inscription",
    signUpSub: "Créez votre compte Green Global Funds",
    fullName: "Nom complet",
    phoneNumber: "Numéro de téléphone",
    confirmPass: "Confirmer le mot de passe",
    agreeTerms: "J'accepte les",
    termsAndCond: "Conditions générales",
    and: "et",
    privacyPolicy: "Politique de confidentialité",
    createAccountBtn: "Créer un compte",
    alreadyAccount: "Vous avez déjà un compte ?",
    addressInfo: "Informations d'adresse",
    streetLabel: "Rue & Numéro",
    streetPlaceholder: "Entrez la rue et le numéro",
    postalLabel: "Code postal",
    postalPlaceholder: "Entrez le code postal",
    cityLabel: "Ville",
    cityPlaceholder: "Entrez votre ville",
    stateLabel: "État / Région",
    selectState: "Sélectionnez un état",
    countryLabel: "Pays",
    back: "Retour",
    continueBtn: "Continuer",
    dashboardTitle: "Tableau de bord",
    dashboardSub: "Bon retour, John ! Voici votre aperçu financier.",
    navDashboard: "Tableau de bord",
    navAccounts: "Comptes",
    navTransactions: "Transactions",
    navInvestments: "Investissements",
    navSavings: "Épargne",
    navLoans: "Prêts",
    navSettings: "Paramètres",
    signOut: "Déconnexion",
    demoUser: "John Doe",
    totalBalance: "Solde total",
    income: "Revenus",
    expenses: "Dépenses",
    savingsGoal: "Objectif d'épargne",
    goalProgress: "68% de l'objectif de 12 000 $",
    investmentsGrowth: "Investissements",
    investmentReturn: "+940,00 $ ce trimestre",
    activeLoans: "Prêts actifs",
    nextPayment: "Prochain paiement : 15 avr.",
    insuranceCoverage: "Assurance",
    fullyCovered: "Entièrement couvert",
    coverageType: "Vie & Santé",
    recentTransactions: "Transactions récentes",
    viewAll: "Voir tout",
    quickActions: "Actions rapides",
    transfer: "Transférer",
    payBills: "Factures",
    invest: "Investir",
    deposit: "Dépôt",
    currencyConverter: "Convertisseur de devises",
    cardInfo: "Informations de carte de débit",
    cardNumber: "Numéro de carte",
    cardholderName: "Titulaire de la carte",
    expiryDate: "Date d'expiration",
    cvv: "CVV",
    cardPlaceholder: "1234 5678 9012 3456",
    namePlaceholder: "Nom complet sur la carte",
    expiryPlaceholder: "MM/AA",
    cvvPlaceholder: "123",
    addCard: "Ajouter la carte",
    skipStep: "Passer pour l'instant"
  },
  es: {
    code: "es",
    lang: "es",
    name: "Spain",
    flag: "🇪🇸",
    label: "Español",
    siteName: "Verde Global",
    siteSuffix: "Fondos",
    navHome: "Inicio",
    navAbout: "Sobre nosotros",
    navServices: "Servicios",
    navHow: "Cómo funciona",
    navBlog: "Blog",
    navContact: "Contacto",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    badgeWelcome: "Bienvenido a Green Global Funds",
    headline: "Haz crecer tu dinero.",
    headlineGreen: "Asegura tu futuro.",
    heroText: "Green Global Funds te ayuda a ahorrar, invertir y hacer crecer tu dinero con soluciones financieras seguras, confiables y rentables.",
    getStarted: "Comenzar",
    learnMore: "Saber más",
    featSecure: "Seguro y confiable",
    featSecureDesc: "Seguridad de nivel bancario para mantener tus fondos seguros.",
    featReturns: "Altos rendimientos",
    featReturnsDesc: "Rendimientos competitivos que ayudan a que tu dinero crezca más rápido.",
    featFast: "Fácil y rápido",
    featFastDesc: "Procesos simples, transacciones rápidas.",
    featSupport: "Soporte 24/7",
    featSupportDesc: "Estamos aquí para ayudarte en cualquier momento y lugar.",
    ourServices: "Nuestros servicios",
    serviceTitle: "Soluciones financieras inteligentes<br>para un mañana mejor",
    serviceSavings: "Ahorros",
    serviceSavingsDesc: "Asegura tu futuro con planes de ahorro flexibles diseñados para ti.",
    serviceInvest: "Inversiones",
    serviceInvestDesc: "Haz crecer tu riqueza con oportunidades de inversión rentables y seguras.",
    serviceLoans: "Préstamos",
    serviceLoansDesc: "Obtén préstamos rápidos y flexibles con opciones de pago fáciles.",
    serviceInsurance: "Seguros",
    serviceInsuranceDesc: "Protege lo que más importa con soluciones de seguros confiables.",
    chooseBadge: "Por qué elegirnos",
    chooseTitle: "Tu confianza, nuestro<br>Compromiso",
    chooseText: "En Green Global Funds, nos comprometemos a proporcionar servicios financieros transparentes, confiables e innovadores que te ayuden a alcanzar tus metas financieras.",
    footerRights: "&copy; 2026 Green Global Funds. Todos los derechos reservados.",
    selectCountry: "Selecciona tu país",
    selectCountryDesc: "Elige tu país para comenzar con la mejor experiencia.",
    continue: "Continuar",
    backToHome: "Volver al inicio",
    signInTitle: "Iniciar sesión",
    signInSub: "Ingresa tus datos para acceder a tu cuenta",
    email: "Correo electrónico",
    password: "Contraseña",
    rememberMe: "Recordarme",
    forgotPassword: "¿Olvidaste tu contraseña?",
    signInBtn: "Iniciar sesión",
    or: "o",
    signInGoogle: "Iniciar sesión con Google",
    noAccount: "¿No tienes cuenta?",
    signUpLink: "Registrarse",
    welcomeBack: "¡Bienvenido de nuevo!",
    signInDesc: "Inicia sesión en tu cuenta y continúa tu viaje financiero con confianza.",
    secureLogin: "Inicio de sesión seguro",
    fastAccess: "Acceso rápido y fácil",
    manageAccount: "Administra tu cuenta",
    createAccount: "Crea tu cuenta",
    signUpDesc: "Únete a miles de personas que confían en Green Global Funds para hacer crecer su dinero de forma segura.",
    secureSafe: "Seguro y protegido",
    easyReg: "Registro fácil",
    startGrowing: "Comienza a crecer hoy",
    signUpTitle: "Registrarse",
    signUpSub: "Crea tu cuenta de Green Global Funds",
    fullName: "Nombre completo",
    phoneNumber: "Número de teléfono",
    confirmPass: "Confirmar contraseña",
    agreeTerms: "Acepto los",
    termsAndCond: "Términos y condiciones",
    and: "y",
    privacyPolicy: "Política de privacidad",
    createAccountBtn: "Crear cuenta",
    alreadyAccount: "¿Ya tienes cuenta?",
    addressInfo: "Información de dirección",
    streetLabel: "Calle y número",
    streetPlaceholder: "Ingresa la calle y el número",
    postalLabel: "Código postal",
    postalPlaceholder: "Ingresa el código postal",
    cityLabel: "Ciudad",
    cityPlaceholder: "Ingresa tu ciudad",
    stateLabel: "Estado / Provincia",
    selectState: "Seleccionar estado",
    countryLabel: "País",
    back: "Atrás",
    continueBtn: "Continuar",
    dashboardTitle: "Panel de control",
    dashboardSub: "¡Bienvenido de nuevo, John! Aquí tienes tu resumen financiero.",
    navDashboard: "Panel",
    navAccounts: "Cuentas",
    navTransactions: "Transacciones",
    navInvestments: "Inversiones",
    navSavings: "Ahorros",
    navLoans: "Préstamos",
    navSettings: "Ajustes",
    signOut: "Cerrar sesión",
    demoUser: "John Doe",
    totalBalance: "Saldo total",
    income: "Ingresos",
    expenses: "Gastos",
    savingsGoal: "Meta de ahorro",
    goalProgress: "68% de la meta de $12,000",
    investmentsGrowth: "Inversiones",
    investmentReturn: "+$940.00 este trimestre",
    activeLoans: "Préstamos activos",
    nextPayment: "Próximo pago: 15 abr.",
    insuranceCoverage: "Seguro",
    fullyCovered: "Completamente cubierto",
    coverageType: "Vida & Salud",
    recentTransactions: "Transacciones recientes",
    viewAll: "Ver todo",
    quickActions: "Acciones rápidas",
    transfer: "Transferir",
    payBills: "Facturas",
    invest: "Invertir",
    deposit: "Depositar",
    currencyConverter: "Conversor de divisas",
    cardInfo: "Información de tarjeta de débito",
    cardNumber: "Número de tarjeta",
    cardholderName: "Titular de la tarjeta",
    expiryDate: "Fecha de vencimiento",
    cvv: "CVV",
    cardPlaceholder: "1234 5678 9012 3456",
    namePlaceholder: "Nombre completo en la tarjeta",
    expiryPlaceholder: "MM/AA",
    cvvPlaceholder: "123",
    addCard: "Añadir tarjeta",
    skipStep: "Saltar por ahora"
  },
  it: {
    code: "it",
    lang: "it",
    name: "Italy",
    flag: "🇮🇹",
    label: "Italiano",
    siteName: "Verde Globale",
    siteSuffix: "Fondi",
    navHome: "Home",
    navAbout: "Chi siamo",
    navServices: "Servizi",
    navHow: "Come funziona",
    navBlog: "Blog",
    navContact: "Contatti",
    signIn: "Accedi",
    signUp: "Registrati",
    badgeWelcome: "Benvenuto su Green Global Funds",
    headline: "Fai crescere i tuoi soldi.",
    headlineGreen: "Assicura il tuo futuro.",
    heroText: "Green Global Funds ti aiuta a risparmiare, investire e far crescere i tuoi soldi con soluzioni finanziarie sicure, affidabili e redditizie.",
    getStarted: "Inizia",
    learnMore: "Scopri di più",
    featSecure: "Sicuro e affidabile",
    featSecureDesc: "Sicurezza di livello bancario per mantenere i tuoi fondi al sicuro.",
    featReturns: "Alti rendimenti",
    featReturnsDesc: "Rendimenti competitivi che aiutano i tuoi soldi a crescere più velocemente.",
    featFast: "Facile e veloce",
    featFastDesc: "Processi semplici, transazioni rapide.",
    featSupport: "Supporto 24/7",
    featSupportDesc: "Siamo qui per aiutarti sempre, ovunque.",
    ourServices: "I nostri servizi",
    serviceTitle: "Soluzioni finanziarie intelligenti<br>per un domani migliore",
    serviceSavings: "Risparmio",
    serviceSavingsDesc: "Assicura il tuo futuro con piani di risparmio flessibili progettati per te.",
    serviceInvest: "Investimenti",
    serviceInvestDesc: "Fai crescere il tuo patrimonio con opportunità di investimento redditizie e sicure.",
    serviceLoans: "Prestiti",
    serviceLoansDesc: "Ottieni prestiti rapidi e flessibili con facili opzioni di rimborso.",
    serviceInsurance: "Assicurazione",
    serviceInsuranceDesc: "Proteggi ciò che conta di più con soluzioni assicurative affidabili.",
    chooseBadge: "Perché sceglierci",
    chooseTitle: "La tua fiducia, il nostro<br>Impegno",
    chooseText: "In Green Global Funds, ci impegniamo a fornire servizi finanziari trasparenti, affidabili e innovativi che ti aiutano a raggiungere i tuoi obiettivi finanziari.",
    footerRights: "&copy; 2026 Green Global Funds. Tutti i diritti riservati.",
    selectCountry: "Seleziona il tuo paese",
    selectCountryDesc: "Scegli il tuo paese per iniziare con la migliore esperienza.",
    continue: "Continua",
    backToHome: "Torna alla home",
    signInTitle: "Accedi",
    signInSub: "Inserisci i tuoi dati per accedere al tuo conto",
    email: "Indirizzo email",
    password: "Password",
    rememberMe: "Ricordami",
    forgotPassword: "Password dimenticata?",
    signInBtn: "Accedi",
    or: "o",
    signInGoogle: "Accedi con Google",
    noAccount: "Non hai un account?",
    signUpLink: "Registrati",
    welcomeBack: "Bentornato!",
    signInDesc: "Accedi al tuo account e continua il tuo percorso finanziario con fiducia.",
    secureLogin: "Accesso sicuro",
    fastAccess: "Accesso facile e veloce",
    manageAccount: "Gestisci il tuo account",
    createAccount: "Crea il tuo account",
    signUpDesc: "Unisciti a migliaia di persone che si fidano di Green Global Funds per far crescere i propri soldi in modo sicuro.",
    secureSafe: "Sicuro e protetto",
    easyReg: "Registrazione facile",
    startGrowing: "Inizia a crescere oggi",
    signUpTitle: "Registrati",
    signUpSub: "Crea il tuo account Green Global Funds",
    fullName: "Nome completo",
    phoneNumber: "Numero di telefono",
    confirmPass: "Conferma password",
    agreeTerms: "Accetto i",
    termsAndCond: "Termini e condizioni",
    and: "e",
    privacyPolicy: "Informativa sulla privacy",
    createAccountBtn: "Crea account",
    alreadyAccount: "Hai già un account?",
    addressInfo: "Informazioni indirizzo",
    streetLabel: "Via e numero",
    streetPlaceholder: "Inserisci via e numero civico",
    postalLabel: "Codice postale",
    postalPlaceholder: "Inserisci il codice postale",
    cityLabel: "Città",
    cityPlaceholder: "Inserisci la tua città",
    stateLabel: "Stato / Provincia",
    selectState: "Seleziona provincia",
    countryLabel: "Paese",
    back: "Indietro",
    continueBtn: "Continua",
    dashboardTitle: "Dashboard",
    dashboardSub: "Bentornato, John! Ecco la tua panoramica finanziaria.",
    navDashboard: "Dashboard",
    navAccounts: "Conti",
    navTransactions: "Transazioni",
    navInvestments: "Investimenti",
    navSavings: "Risparmio",
    navLoans: "Prestiti",
    navSettings: "Impostazioni",
    signOut: "Esci",
    demoUser: "John Doe",
    totalBalance: "Saldo totale",
    income: "Entrate",
    expenses: "Uscite",
    savingsGoal: "Obiettivo risparmio",
    goalProgress: "68% dell'obiettivo di $12.000",
    investmentsGrowth: "Investimenti",
    investmentReturn: "+$940,00 in questo trimestre",
    activeLoans: "Prestiti attivi",
    nextPayment: "Prossimo pagamento: 15 apr.",
    insuranceCoverage: "Assicurazione",
    fullyCovered: "Completamente coperto",
    coverageType: "Vita & Salute",
    recentTransactions: "Transazioni recenti",
    viewAll: "Vedi tutto",
    quickActions: "Azioni rapide",
    transfer: "Trasferisci",
    payBills: "Bollette",
    invest: "Investi",
    deposit: "Deposita",
    currencyConverter: "Convertitore valuta",
    cardInfo: "Informazioni carta di debito",
    cardNumber: "Numero di carta",
    cardholderName: "Intestatario della carta",
    expiryDate: "Data di scadenza",
    cvv: "CVV",
    cardPlaceholder: "1234 5678 9012 3456",
    namePlaceholder: "Nome completo sulla carta",
    expiryPlaceholder: "MM/AA",
    cvvPlaceholder: "123",
    addCard: "Aggiungi carta",
    skipStep: "Salta per ora"
  },
  br: {
    code: "br",
    lang: "pt",
    name: "Brazil",
    flag: "🇧🇷",
    label: "Português",
    siteName: "Verde Global",
    siteSuffix: "Fundos",
    navHome: "Início",
    navAbout: "Sobre nós",
    navServices: "Serviços",
    navHow: "Como funciona",
    navBlog: "Blog",
    navContact: "Contato",
    signIn: "Entrar",
    signUp: "Cadastrar",
    badgeWelcome: "Bem-vindo à Green Global Funds",
    headline: "Faça seu dinheiro crescer.",
    headlineGreen: "Garanta seu futuro.",
    heroText: "A Green Global Funds ajuda você a poupar, investir e fazer seu dinheiro crescer com soluções financeiras seguras, confiáveis e rentáveis.",
    getStarted: "Começar",
    learnMore: "Saiba mais",
    featSecure: "Seguro e confiável",
    featSecureDesc: "Segurança de nível bancário para manter seus fundos seguros.",
    featReturns: "Altos rendimentos",
    featReturnsDesc: "Rendimentos competitivos que fazem seu dinheiro crescer mais rápido.",
    featFast: "Fácil e rápido",
    featFastDesc: "Processos simples, transações rápidas.",
    featSupport: "Suporte 24/7",
    featSupportDesc: "Estamos aqui para ajudar você a qualquer hora, em qualquer lugar.",
    ourServices: "Nossos serviços",
    serviceTitle: "Soluções financeiras inteligentes<br>para um amanhã melhor",
    serviceSavings: "Poupança",
    serviceSavingsDesc: "Garanta seu futuro com planos de poupança flexíveis projetados para você.",
    serviceInvest: "Investimentos",
    serviceInvestDesc: "Faça seu patrimônio crescer com oportunidades de investimento rentáveis e seguras.",
    serviceLoans: "Empréstimos",
    serviceLoansDesc: "Obtenha empréstimos rápidos e flexíveis com opções de pagamento fáceis.",
    serviceInsurance: "Seguros",
    serviceInsuranceDesc: "Proteja o que é mais importante com soluções de seguro confiáveis.",
    chooseBadge: "Por que nos escolher",
    chooseTitle: "Sua confiança, nosso<br>Compromisso",
    chooseText: "Na Green Global Funds, estamos comprometidos em fornecer serviços financeiros transparentes, confiáveis e inovadores que ajudam você a alcançar seus objetivos financeiros.",
    footerRights: "&copy; 2026 Green Global Funds. Todos os direitos reservados.",
    selectCountry: "Selecione seu país",
    selectCountryDesc: "Escolha seu país para começar com a melhor experiência.",
    continue: "Continuar",
    backToHome: "Voltar ao início",
    signInTitle: "Entrar",
    signInSub: "Insira seus detalhes para acessar sua conta",
    email: "Endereço de e-mail",
    password: "Senha",
    rememberMe: "Lembrar de mim",
    forgotPassword: "Esqueceu a senha?",
    signInBtn: "Entrar",
    or: "ou",
    signInGoogle: "Entrar com Google",
    noAccount: "Não tem uma conta?",
    signUpLink: "Cadastrar",
    welcomeBack: "Bem-vindo de volta!",
    signInDesc: "Faça login na sua conta e continue sua jornada financeira com confiança.",
    secureLogin: "Login seguro",
    fastAccess: "Acesso rápido e fácil",
    manageAccount: "Gerencie sua conta",
    createAccount: "Crie sua conta",
    signUpDesc: "Junte-se a milhares de pessoas que confiam na Green Global Funds para fazer seu dinheiro crescer com segurança.",
    secureSafe: "Seguro e protegido",
    easyReg: "Cadastro fácil",
    startGrowing: "Comece a crescer hoje",
    signUpTitle: "Cadastrar",
    signUpSub: "Crie sua conta na Green Global Funds",
    fullName: "Nome completo",
    phoneNumber: "Número de telefone",
    confirmPass: "Confirmar senha",
    agreeTerms: "Concordo com os",
    termsAndCond: "Termos e Condições",
    and: "e",
    privacyPolicy: "Política de Privacidade",
    createAccountBtn: "Criar conta",
    alreadyAccount: "Já tem uma conta?",
    addressInfo: "Informações de endereço",
    streetLabel: "Rua e número",
    streetPlaceholder: "Digite a rua e o número",
    postalLabel: "CEP",
    postalPlaceholder: "Digite seu CEP",
    cityLabel: "Cidade",
    cityPlaceholder: "Digite sua cidade",
    stateLabel: "Estado",
    selectState: "Selecione o estado",
    countryLabel: "País",
    back: "Voltar",
    continueBtn: "Continuar",
    dashboardTitle: "Painel",
    dashboardSub: "Bem-vindo de volta, John! Aqui está sua visão geral financeira.",
    navDashboard: "Painel",
    navAccounts: "Contas",
    navTransactions: "Transações",
    navInvestments: "Investimentos",
    navSavings: "Poupança",
    navLoans: "Empréstimos",
    navSettings: "Configurações",
    signOut: "Sair",
    demoUser: "João Silva",
    totalBalance: "Saldo total",
    income: "Receitas",
    expenses: "Despesas",
    savingsGoal: "Meta de poupança",
    goalProgress: "68% da meta de $12.000",
    investmentsGrowth: "Investimentos",
    investmentReturn: "+$940,00 neste trimestre",
    activeLoans: "Empréstimos ativos",
    nextPayment: "Próximo pagamento: 15 abr.",
    insuranceCoverage: "Seguro",
    fullyCovered: "Totalmente coberto",
    coverageType: "Vida & Saúde",
    recentTransactions: "Transações recentes",
    viewAll: "Ver tudo",
    quickActions: "Ações rápidas",
    transfer: "Transferir",
    payBills: "Contas",
    invest: "Investir",
    deposit: "Depositar",
    currencyConverter: "Conversor de moedas",
    cardInfo: "Informações do cartão de débito",
    cardNumber: "Número do cartão",
    cardholderName: "Titular do cartão",
    expiryDate: "Data de validade",
    cvv: "CVV",
    cardPlaceholder: "1234 5678 9012 3456",
    namePlaceholder: "Nome completo no cartão",
    expiryPlaceholder: "MM/AA",
    cvvPlaceholder: "123",
    addCard: "Adicionar cartão",
    skipStep: "Pular por agora"
  },
  ng: {
    code: "ng",
    lang: "en",
    name: "Nigeria",
    flag: "🇳🇬",
    label: "English",
    siteName: "Green Global",
    siteSuffix: "Funds",
    navHome: "Home",
    navAbout: "About Us",
    navServices: "Services",
    navHow: "How It Works",
    navBlog: "Blog",
    navContact: "Contact",
    signIn: "Sign In",
    signUp: "Sign Up",
    badgeWelcome: "Welcome to Green Global Funds",
    headline: "Grow Your Money.",
    headlineGreen: "Secure Your Future.",
    heroText: "Green Global Funds helps you save, invest and grow your money with secure, reliable and profitable financial solutions.",
    getStarted: "Get Started",
    learnMore: "Learn More",
    featSecure: "Secure & Trusted",
    featSecureDesc: "Bank-level security to keep your funds safe.",
    featReturns: "High Returns",
    featReturnsDesc: "Competitive returns that help your money grow faster.",
    featFast: "Easy & Fast",
    featFastDesc: "Simple processes, quick transactions.",
    featSupport: "24/7 Support",
    featSupportDesc: "We are here to help you anytime, anywhere.",
    ourServices: "Our Services",
    serviceTitle: "Smart Financial Solutions<br>for a Better Tomorrow",
    serviceSavings: "Savings",
    serviceSavingsDesc: "Secure your future with flexible savings plans designed for you.",
    serviceInvest: "Investments",
    serviceInvestDesc: "Grow your wealth with profitable and secure investment opportunities.",
    serviceLoans: "Loans",
    serviceLoansDesc: "Get quick and flexible loans with easy repayment options.",
    serviceInsurance: "Insurance",
    serviceInsuranceDesc: "Protect what matters most with reliable insurance solutions.",
    chooseBadge: "Why Choose Us",
    chooseTitle: "Your Trust, Our<br>Commitment",
    chooseText: "At Green Global Funds, we are committed to providing transparent, reliable, and innovative financial services that help you achieve your financial goals.",
    footerRights: "&copy; 2026 Green Global Funds. All rights reserved.",
    selectCountry: "Select Your Country",
    selectCountryDesc: "Choose your country to get started with the best experience.",
    continue: "Continue",
    backToHome: "Back to Home",
    signInTitle: "Sign In",
    signInSub: "Enter your details to access your account",
    email: "Email Address",
    password: "Password",
    rememberMe: "Remember Me",
    forgotPassword: "Forgot Password?",
    signInBtn: "Sign In",
    or: "or",
    signInGoogle: "Sign in with Google",
    noAccount: "Don't have an account?",
    signUpLink: "Sign Up",
    welcomeBack: "Welcome Back!",
    signInDesc: "Sign in to your account and continue your financial journey with confidence.",
    secureLogin: "Secure Login",
    fastAccess: "Fast & Easy Access",
    manageAccount: "Manage Your Account",
    createAccount: "Create Your Account",
    signUpDesc: "Join thousands of people who trust Green Global Funds to grow their money securely.",
    secureSafe: "Secure & Safe",
    easyReg: "Easy Registration",
    startGrowing: "Start Growing Today",
    signUpTitle: "Sign Up",
    signUpSub: "Create your Green Global Funds account",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    confirmPass: "Confirm Password",
    agreeTerms: "I agree to the",
    termsAndCond: "Terms and Conditions",
    and: "and",
    privacyPolicy: "Privacy Policy",
    createAccountBtn: "Create Account",
    alreadyAccount: "Already have an account?",
    addressInfo: "Address Information",
    streetLabel: "Street & House Number",
    streetPlaceholder: "Enter street and house number",
    postalLabel: "Postal Code",
    postalPlaceholder: "Enter postal code",
    cityLabel: "City",
    cityPlaceholder: "Enter your city",
    stateLabel: "State / Federal State",
    selectState: "Select state",
    countryLabel: "Country",
    back: "Back",
    continueBtn: "Continue",
    dashboardTitle: "Dashboard",
    dashboardSub: "Welcome back, John! Here's your financial overview.",
    navDashboard: "Dashboard",
    navAccounts: "Accounts",
    navTransactions: "Transactions",
    navInvestments: "Investments",
    navSavings: "Savings",
    navLoans: "Loans",
    navSettings: "Settings",
    signOut: "Sign Out",
    demoUser: "John Doe",
    totalBalance: "Total Balance",
    income: "Income",
    expenses: "Expenses",
    savingsGoal: "Savings Goal",
    goalProgress: "68% of $12,000 goal",
    investmentsGrowth: "Investments",
    investmentReturn: "+$940.00 this quarter",
    activeLoans: "Active Loans",
    nextPayment: "Next payment: Apr 15",
    insuranceCoverage: "Insurance",
    fullyCovered: "Fully Covered",
    coverageType: "Life & Health",
    recentTransactions: "Recent Transactions",
    viewAll: "View All",
    quickActions: "Quick Actions",
    transfer: "Transfer",
    payBills: "Pay Bills",
    invest: "Invest",
    deposit: "Deposit",
    currencyConverter: "Currency Converter",
    cardInfo: "Debit Card Information",
    cardNumber: "Card Number",
    cardholderName: "Cardholder Name",
    expiryDate: "Expiry Date",
    cvv: "CVV",
    cardPlaceholder: "1234 5678 9012 3456",
    namePlaceholder: "Full Name on Card",
    expiryPlaceholder: "MM/YY",
    cvvPlaceholder: "123",
    addCard: "Add Card",
    skipStep: "Skip for now"
  }
};

const COUNTRIES = [
  { code: "us", name: "United States", flag: "🇺🇸", lang: "en" },
  { code: "gb", name: "United Kingdom", flag: "🇬🇧", lang: "en" },
  { code: "de", name: "Germany", flag: "🇩🇪", lang: "de" },
  { code: "fr", name: "France", flag: "🇫🇷", lang: "fr" },
  { code: "es", name: "Spain", flag: "🇪🇸", lang: "es" },
  { code: "it", name: "Italy", flag: "🇮🇹", lang: "it" },
  { code: "ng", name: "Nigeria", flag: "🇳🇬", lang: "en" },
  { code: "br", name: "Brazil", flag: "🇧🇷", lang: "pt" }
];

const CURRENT_COUNTRY_COOKIE = "green_global_country";

function getSelectedCountry() {
  const code = localStorage.getItem(CURRENT_COUNTRY_COOKIE);
  if (code && TRANSLATIONS[code]) {
    return TRANSLATIONS[code];
  }
  return null;
}

function setSelectedCountry(code) {
  localStorage.setItem(CURRENT_COUNTRY_COOKIE, code);
}

function initLanguageSelector() {
  const saved = getSelectedCountry();
  if (!saved) {
    showLanguageOverlay();
  } else {
    applyTranslation(saved);
  }
}

function showLanguageOverlay() {
  const overlay = document.getElementById("country-overlay");
  if (overlay) overlay.classList.remove("hidden");
}

function applyTranslation(t) {
  document.documentElement.lang = t.lang;

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (t[key]) {
      el.innerHTML = t[key];
    }
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (t[key]) {
      el.placeholder = t[key];
    }
  });

  // Set the flag icon if it exists in the nav
  const flagEl = document.getElementById("current-flag");
  if (flagEl) flagEl.textContent = t.flag;

  const countryNameEl = document.getElementById("current-country-name");
  if (countryNameEl) countryNameEl.textContent = t.name;
}

function selectCountry(code) {
  setSelectedCountry(code);
  const t = TRANSLATIONS[code];
  if (t) {
    applyTranslation(t);
  }
  const overlay = document.getElementById("country-overlay");
  if (overlay) overlay.classList.add("hidden");
}

function buildCountryOverlay() {
  const overlay = document.createElement("div");
  overlay.id = "country-overlay";
  overlay.className = "fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm transition-all duration-300";

  const saved = getSelectedCountry();
  if (saved) {
    overlay.classList.add("hidden");
  }

  overlay.innerHTML = `
    <div class="bg-white rounded-3xl shadow-2xl w-full max-w-lg mx-4 p-8 animate-fade-in">
      <div class="text-center mb-8">
        <div class="w-16 h-16 bg-brand-green text-white rounded-full flex items-center justify-center text-3xl mx-auto mb-4 shadow-lg">
          <i class="fas fa-globe"></i>
        </div>
        <h2 class="text-2xl font-bold text-gray-900" data-i18n="selectCountry">Select Your Country</h2>
        <p class="text-gray-400 text-sm mt-2" data-i18n="selectCountryDesc">Choose your country to get started with the best experience.</p>
      </div>
      <div class="grid grid-cols-1 gap-3 max-h-80 overflow-y-auto pr-1">
        ${COUNTRIES.map(c => `
          <button onclick="selectCountry('${c.code}')"
            class="country-option flex items-center space-x-4 w-full p-4 rounded-xl border border-gray-100 hover:border-brand-green hover:bg-green-50 transition text-left group">
            <span class="text-3xl">${c.flag}</span>
            <div class="flex-1">
              <span class="font-semibold text-gray-800 text-sm group-hover:text-brand-green transition">${c.name}</span>
              <span class="block text-xs text-gray-400">${TRANSLATIONS[c.code].label}</span>
            </div>
            <i class="fas fa-chevron-right text-gray-300 text-xs group-hover:text-brand-green transition"></i>
          </button>
        `).join("")}
      </div>
    </div>
  `;

  document.body.appendChild(overlay);

  // Add animation style
  const style = document.createElement("style");
  style.textContent = `
    @keyframes fadeIn {
      from { opacity: 0; transform: scale(0.95); }
      to { opacity: 1; transform: scale(1); }
    }
    .animate-fade-in {
      animation: fadeIn 0.3s ease-out;
    }
  `;
  document.head.appendChild(style);
}